# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45771f71e5af11404321c2d3a358bf0f636fc1f03f8d75de2da1ee05898334c1bae8c371227196194d3221f9e56ca5a7d8d8d10a78f3212241fa93c8ec4eec7f

test:
  secret_key_base: 5460993ad8d4bf8a2a527df203d43ebdaf28cbaf3fd34d48eb40ddbfaecc5579f75652ceb7f6de367e09a77683b65c63d69fab74643aa3c4a259d7e1db14deb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
